### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mbuhot** [PagerDuty/db2kafka#2]
This looks like a cool project, but I didn't see a license file.

Could you please add an MIT license or similar so that I could make use of this app?

Thanks!

**Comment by cdegroot** [comment]
Oops. Thanks for that, I'll add the MIT license (per https://hex.pm/packages/db2kafka)

**Comment by cdegroot** [comment]
Added it to the README.

**Comment by mbuhot** [comment]
Awesome, thanks!
